
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
#  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3-openjdk-17
  script:
    - echo "Compiling the code..."
    - "mvn clean package -B -Dmaven.test.skip"
    - echo "Compile complete."
  artifacts:
    paths:
      - target/*.jar    


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: maven:3-openjdk-17
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - "mvn test"
    - echo "Code coverage is 90%"
  artifacts:
    paths:
      - "**/target/" 
    reports:
      junit: 
       - "**/target/*-reports/TEST-*.xml"    

